'use client';
import {Children,isValidElement,useEffect,useId,useRef,useState,type ReactNode,type SelectHTMLAttributes} from 'react';
import {ChevronDown,Check,X} from 'lucide-react';
export function SoftSelect(props:SelectHTMLAttributes<HTMLSelectElement>){
 const {children,name,value,defaultValue,onChange,disabled,required}=props;const [local,setLocal]=useState(String(defaultValue??''));const [open,setOpen]=useState(false);const current=String(value??local);const menu=useRef<HTMLDivElement>(null);const trigger=useRef<HTMLButtonElement>(null);const id=useId();
 const options=Children.toArray(children).filter(isValidElement).map(child=>{const p=child.props as {value:string|number;children:ReactNode;disabled?:boolean};return {value:String(p.value),label:p.children,disabled:p.disabled};});
 const selected=options.find(o=>o.value===current)||options[0];
 function position(){const r=trigger.current?.getBoundingClientRect();const el=menu.current;if(!r||!el)return;el.style.left=Math.max(8,Math.min(r.left,innerWidth-r.width-8))+'px';el.style.width=Math.min(r.width,innerWidth-16)+'px';const below=innerHeight-r.bottom-12;const above=r.top-12;const up=below<150&&above>below;el.style.maxHeight=Math.max(80,Math.min(300,up?above:below))+'px';el.style.top=(up?Math.max(8,r.top-el.offsetHeight-6):r.bottom+6)+'px';}
 useEffect(()=>{if(!open)return;position();window.addEventListener('resize',position);window.addEventListener('scroll',position,true);return()=>{window.removeEventListener('resize',position);window.removeEventListener('scroll',position,true);};},[open]);
 function close(){menu.current?.hidePopover();trigger.current?.focus();}
 const choose=(v:string)=>{setLocal(v);onChange?.({target:{value:v},currentTarget:{value:v}} as React.ChangeEvent<HTMLSelectElement>);close();};
 function show(){menu.current?.showPopover();position();}
 return <span className="soft-select"><input type="hidden" name={name} value={selected?.value||''} disabled={disabled}/><button ref={trigger} type="button" disabled={disabled} aria-haspopup="listbox" aria-expanded={open} aria-controls={id} aria-required={required} className="select-trigger" onClick={()=>open?close():show()} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();show();menu.current?.querySelector<HTMLButtonElement>('[aria-selected=true]')?.focus();}}}>{selected?.label}<ChevronDown size={18}/></button><div ref={menu} popover="auto" id={id} className="select-dropdown" role="listbox" aria-label="Các lựa chọn" onToggle={e=>setOpen((e as unknown as {newState:string}).newState==='open')} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();return;}if(e.key==='Tab'){menu.current?.hidePopover();return;}if(!['ArrowDown','ArrowUp','Home','End'].includes(e.key))return;e.preventDefault();const items=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)'));const at=items.indexOf(document.activeElement as HTMLButtonElement);const next=e.key==='Home'?0:e.key==='End'?items.length-1:e.key==='ArrowDown'?(at+1)%items.length:(at-1+items.length)%items.length;items[next]?.focus();}}>{options.map(o=><button type="button" role="option" aria-selected={selected?.value===o.value} disabled={o.disabled} key={o.value} onClick={()=>choose(o.value)} className="choice-option">{o.label}{selected?.value===o.value&&<Check size={18}/>}</button>)}</div></span>;
}
export function askConfirmation(message:string):Promise<boolean>{return new Promise(resolve=>window.dispatchEvent(new CustomEvent('mihu-confirm',{detail:{message,resolve}})));}
export function ConfirmationHost(){const [pending,setPending]=useState<{message:string;resolve:(v:boolean)=>void}|null>(null);const ref=useRef<HTMLDialogElement>(null);const active=useRef<typeof pending>(null);
 useEffect(()=>{const handler=(e:Event)=>{active.current?.resolve(false);const item=(e as CustomEvent).detail;active.current=item;setPending(item);};window.addEventListener('mihu-confirm',handler);return()=>{window.removeEventListener('mihu-confirm',handler);active.current?.resolve(false);};},[]);
 useEffect(()=>{if(pending)ref.current?.showModal();},[pending]);
 function finish(ok:boolean){pending?.resolve(ok);active.current=null;setPending(null);}
 return pending?<dialog ref={ref} className="choice-dialog" onCancel={e=>{e.preventDefault();finish(false);}} aria-labelledby="confirm-heading"><h2 id="confirm-heading">Mihu xác nhận nhé</h2><p className="confirm-message">{pending.message}</p><div className="form-actions"><button type="button" autoFocus className="button" onClick={()=>finish(false)}>Hủy</button><button type="button" className="button primary" onClick={()=>finish(true)}>Đồng ý</button></div></dialog>:null;
}
