import {registerHooks} from 'node:module';
import {loadEnvFile} from 'node:process';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import ts from 'typescript';
try{loadEnvFile('.env.local');}catch{}
const root=process.cwd();const bindings=new URL('./local-bindings.mjs',import.meta.url).href;
registerHooks({resolve(specifier,context,nextResolve){if(specifier==='cloudflare:workers'||specifier==='next/headers')return {url:bindings,shortCircuit:true};if(specifier.startsWith('@/'))specifier=pathToFileURL(path.join(root,specifier.slice(2))).href;if((specifier.startsWith('.')||specifier.startsWith('file:'))&&context.parentURL?.startsWith(pathToFileURL(root).href)){const u=new URL(specifier,context.parentURL);if(!path.extname(u.pathname)){for(const ext of ['.ts','.tsx','.mjs','.js'])if(fs.existsSync(fileURLToPath(u)+ext))return {url:u.href+ext,shortCircuit:true};}}return nextResolve(specifier,context);},load(url,context,nextLoad){if(url.startsWith(pathToFileURL(root).href)&&url.endsWith('.ts')&&!url.includes('/node_modules/'))return {format:'module',source:ts.transpileModule(fs.readFileSync(fileURLToPath(url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText,shortCircuit:true};return nextLoad(url,context);}});
const {requestContext}=await import(bindings);
const routeNames=['auth','state','assets','push','reminders'];const routes={};for(const name of routeNames)routes['/api/'+name]=await import(pathToFileURL(path.join(root,'app/api',name,'route.ts')).href);
export async function handleBackend(req,res){const pathname=new URL(req.url,'http://127.0.0.1:5173').pathname;const route=routes[pathname];if(!route){res.writeHead(404);res.end();return;}const cookieMap=new Map((req.headers.cookie||'').split(';').map(v=>{const at=v.indexOf('=');return [v.slice(0,at).trim(),decodeURIComponent(v.slice(at+1))];}));const ctx={cookies:cookieMap,setCookies:[]};await requestContext.run(ctx,async()=>{try{const chunks=[];let length=0;for await(const chunk of req){length+=chunk.length;if(length>8*1024*1024){res.writeHead(413);res.end();return;}chunks.push(chunk);}const request=new Request('http://127.0.0.1:5173'+req.url,{method:req.method,headers:req.headers,body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(chunks)});const handler=route[req.method];const response=handler?await handler(request):new Response(null,{status:405});res.statusCode=response.status;response.headers.forEach((v,k)=>res.setHeader(k,v));if(ctx.setCookies.length)res.setHeader('Set-Cookie',ctx.setCookies);res.end(Buffer.from(await response.arrayBuffer()));}catch(e){console.error('Local request failed:',e.name);res.writeHead(500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'Kết nối đang gặp lỗi. Nội dung chưa được lưu.'}));}});}
